### ISSUE TITLE
[question] change css parameters

### ISSUE THREAD

**Issue by empereira** [voluntadpear/vue-choropleth#22]
hi,

Is it possible to change parameters in CSS, for example, of the tags l-info-control?

Inspect style:
![image](https://user-images.githubusercontent.com/29874574/86710786-b4d36d80-bff1-11ea-8165-a8d6f9ed230d.png)

**Comment by srisaiyeegharan** [comment]
I need help with this as well. Were you able to get around to this?

**Comment by empereira** [comment]
> I need help with this as well. Were you able to get around to this?

No. Apparently the repository maintainer doesn't check anything here anymore.

**Comment by srisaiyeegharan** [comment]
Oh okai, idk why but my colour is coming as blue. Can't seem to change it. 
![image](https://user-images.githubusercontent.com/13778035/88534154-cfc25c00-d04a-11ea-89b5-2ad31e6be333.png)

**Comment by empereira** [comment]
For me too. Did you try to modify the plugin css internally?

They stay in the node_modules folder.

![image](https://user-images.githubusercontent.com/29874574/88575645-9a057f00-d01a-11ea-8ce2-82325b767497.png)

![image](https://user-images.githubusercontent.com/29874574/88575838-de911a80-d01a-11ea-9aa7-b903726f7d9f.png)

It seems that the background setting is "white", but there is something forcing him to "blue". Are you using another plugin, like vuelayers or vue2-leaflet?

**Comment by L-J-P** [comment]
My l-info-control background is also blue. I'm using Vuetify and it seems that the blue is coming from Vuetify's theme for the "info" color.

This .info class in this component also causes me issues with the Vuetify's own "info" CSS. After I have visited on the view with the Vue-Choropleth -component and then move to another view, some of the Vuetify's elements look wrong. This seems to be because Vue-Choropleth .info CSS is remembered by browser and overrides Vuetify's "info" CSS.

Could this .info class be renamed to something else? Or is it possible to set this components style to scoped?
