### ISSUE TITLE
Change stroke color

### ISSUE THREAD

**Issue by skarampatakis** [voluntadpear/vue-choropleth#5]
Currently polygon strokes defaults to white, and grey when mouseover. Could this be customizable?

**Comment by plicplic** [comment]
Hi @skarampatakis and @voluntadpear,
I face the same problem and would like to change stroke and weight values. Is there any way to modify the source of the component to achieve this?

**Comment by voluntadpear** [comment]
Hi @skarampatakis and @plicplic 

I've just published `v0.2.0` with new props on the `ChroplethLayer` for setting the color of the strokes. They are `strokeColor` and `currentStrokeColor`. Check the `README.md` for the full description, but basically you just need to provide the hex color as an String for those props.

btw, this new release updates `Vue2Leaflet` to the latest version, and the components use now `l-` as a prefix instead of `v-`. To maintain consistency with `Vue2Leaflet`. 

Please, let me know if this new version work with you and if the new props are useful.

Closing this issue.

**Comment by voluntadpear** [comment]
Oh, I forgot about the `strokeWidth` setting. I added props for that as well, `strokeWidth` and `currentStrokeWidth`.

**Comment by plicplic** [comment]
Hi @voluntadpear,
I began to play with the new props. It's a very welcomed update. Thanks for taking the time!
